name: Build and deploy Node.js app to Azure Web App - ejs-template

on:
  push:
    branches:
      - master

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    environment: production

    steps:
      - uses: actions/checkout@v2

      - name: Set up Node.js version
        uses: actions/setup-node@v2
        with:
          node-version: '14.x'

      - name: npm install, build, and test
        run: |
          npm install
          npm run build --if-present
          npm run test --if-present

  deploy:
    name: Deploy 
    runs-on: ubuntu-latest
    needs: build
    environment: 'Production'

    steps:
      - uses: actions/checkout@v2

      - name: Use Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14.x'

      - name: 'Deploy to Azure WebApp'
        uses: azure/webapps-deploy@v2
        with:
          app-name: 'ejs-template'
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_1743AC996B0049D38AA12D4A255844C0 }}
          package: .  